### ISSUE TITLE
Segmentation fault crash on OBS Studio 26.0.0

### ISSUE THREAD

**Issue by alexitx** [ujifgc/obs-audio-writer-filter#1]
Adding 'Audio Writer' filter on a Mic/Aux device causes segmentation fault which leads to OBS exitting immediately after the crash message popup.

Reproduced using `OBS Studio 26.0 x64 Portable`:

1. Install Audio Writer Filter
2. Launch OBS with `--portable` or `-p` argument
3. In audio settings select the appropriate Desktop and Mic/Aux devices
4. Add 'Audio Writer' filter to the Desktop Audio device - No issues
5. Add 'Audio Writer' filter to the Mix/Aux device - Crash

System:

```
Windows 10 2004 19041.450 x64
Realtek Audio Driver 6.0.1.8273
Built-in audio on Asus Prime Z270-A
```

[Crash report](https://paste.gg/p/anonymous/842ef5f192744601b76e10f85a28077c/files/ddfdfd46f0454de69b4f8daac9b17228/raw)
[Log](https://paste.gg/p/anonymous/842ef5f192744601b76e10f85a28077c/files/7a7ac5dda97e44579c5aff9573f74614/raw)

**Comment by ujifgc** [comment]
Should be fixed in https://github.com/ujifgc/obs-audio-writer-filter/releases/tag/1.4
