### ISSUE TITLE
Doesn't work on OBS Studio 27.0.1

### ISSUE THREAD

**Issue by alexitx** [ujifgc/obs-audio-writer-filter#2]
Creates empty 44 byte file. No crashes or errors in log.

[OBS log](https://paste.gg/p/anonymous/0b30cc1e1c3b49ef9ba7fe51cf66525d/files/2d8602cde837458297323c7bf42cdaa2/raw)

Windows 10 20H2 19042.746
OBS Studio 27.0.1
Audio Writer Filter 1.4

**Comment by ujifgc** [comment]
Should be fixed with the new rebuild. https://github.com/ujifgc/obs-audio-writer-filter/releases/tag/1.27

Sorry for the inconvenience, this plugin is very dependent on internal OBS ABI so it has to be rebuilt for every time they change something major.

**Comment by alexitx** [comment]
I see. It's a very useful tool and there's no alternative as far as I know. Maybe you could set up a CI using Github Actions to test and build automatically or have a manual workflow for convenience.
