### ISSUE TITLE
experiencing crashes on obs v27.2.1

### ISSUE THREAD

**Issue by JoqniX** [ujifgc/obs-audio-writer-filter#5]
Yahallo~ 
i just installed audio writer plugin~ and wanted to use it for a recording. but sadly i've been experiencing alot of crashes. when i enable the filter on my mic source. ( yesh its in .wav format and it crashes. i tried aac too it also crashes (yeshh the encoder is also installed too)  so it crashes after adding the filter and turning it on. 

i am on windows 11 Pro 
Version 21H2 ( OS Build - 22000.527)

OBS - v27.2.1

Audio Writer Filter - v1.27 ( latest one ) https://github.com/ujifgc/obs-audio-writer-filter/releases/tag/1.27

here are the crash logs 
[Crash 2022-02-28 17-29-19.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8154046/Crash.2022-02-28.17-29-19.txt)
[Crash 2022-02-28 17-29-43.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8154047/Crash.2022-02-28.17-29-43.txt)
[Crash 2022-02-28 18-31-51.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8154048/Crash.2022-02-28.18-31-51.txt)
[Crash 2022-02-28 18-45-12.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8154049/Crash.2022-02-28.18-45-12.txt)
[Crash 2022-02-28 18-56-13.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8154050/Crash.2022-02-28.18-56-13.txt)

yesh one of them crash logs had completed removed my audio devices etc and after saving the crash file and when obs had closed down, i got my audio drivers back again. 
![image](https://user-images.githubusercontent.com/54277349/156001152-80b86388-8eb7-4ec0-b5d7-03bc316eaa48.png)

btw, i wanted say that~ thank you for making this wonderful plugin~ arigato for your hardwork nee~ 💕 cant wait to fully use it~ once its fixed <3
kind regards,
JoqniX

**Comment by Lordmau5** [comment]
Experiencing the same issue on v27.2.4
[Crash 2022-04-05 12-32-19.txt](https://github.com/ujifgc/obs-audio-writer-filter/files/8417257/Crash.2022-04-05.12-32-19.txt)

**Comment by ujifgc** [comment]
https://github.com/ujifgc/obs-audio-writer-filter/releases/tag/1.28
