### ISSUE TITLE
Can't read audio fails later

### ISSUE THREAD

**Issue by Katzyh** [ujifgc/obs-audio-writer-filter#7]
Hey, I tryed with all different encoders and different programs to open the audio files but no use. Also tryed converting.
With different programs I get different errors like encoding error, file is corrupted etc etc. 
Even tryed different formats but nope, same. 
This plugin is exactly what I need to save dj set seperatly from video.

**Comment by Katzyh** [comment]
U mean audio file right? 
[ [unknown] 2023-12-02 10-22-39.zip](https://github.com/ujifgc/obs-audio-writer-filter/files/13583667/unknown.2023-12-02.10-22-39.zip)

**Comment by Katzyh** [comment]
Oh. I added filter to audio interface Behringer Xenyx 302USB, which is then connected to a Dj controller.

**Comment by Katzyh** [comment]
From there I got all disabled, its added as audio input capture

**Comment by ujifgc** [comment]
Should work for audio input capture. What versions of OBS and the plugin you have?

**Comment by Katzyh** [comment]
Is working now. Perfect. Thank you.
